services:
  db-service:
    image: db-service
    build:
      context: .
    environment:
      S3FS_ENDPOINT: http://minio:9000
      S3FS_BUCKET: test
      S3FS_REGION: us-east-1 # default region for s3-compatible APIs
      S3FS_MOUNT: /mnt/s3
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    ports:
      - 5432:5432
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    depends_on:
      minio:
        condition: service_healthy
  tls-init:
    image: tls-init
    build:
      context: .
    environment:
      S3FS_ENDPOINT: http://minio:9000
      S3FS_BUCKET: test
      S3FS_REGION: us-east-1 # default region for s3-compatible APIs
      S3FS_MOUNT: /mnt/s3
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    command: ./scripts/generate-certs.sh
    depends_on:
      minio:
        condition: service_healthy
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9000:9000
    command: server /data
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 5s
      timeout: 5s
      retries: 1
  minio-init:
    image: minio/mc
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio:9000 minioadmin minioadmin;
        (mc ls local/test || mc mb local/test);
      "
    depends_on:
      minio:
        condition: service_healthy
